# Generated by Django 3.0.2 on 2021-04-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionNosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('imagen', models.ImageField(upload_to='secciones/')),
            ],
            options={
                'verbose_name': 'Sección Nosotros',
                'verbose_name_plural': '01 - Sección Nosotros',
            },
        ),
    ]
