# Generated by Django 3.0.2 on 2021-04-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0002_seccionnosotros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccionnosotros',
            options={'verbose_name': 'Sección Nosotros', 'verbose_name_plural': '02 - Sección Nosotros'},
        ),
    ]
