# Generated by Django 3.0.2 on 2021-04-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0003_auto_20210410_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.TextField()),
            ],
            options={
                'verbose_name': 'Coordenada',
                'verbose_name_plural': '03 - Coordenadas',
            },
        ),
    ]
