# Generated by Django 3.0.2 on 2021-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0004_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionprincipal',
            name='enlace',
            field=models.CharField(choices=[('productos', 'Ver productos'), ('servicios', 'Ver servicios'), ('blog', 'Historias'), ('contacto', 'Contáctenos')], max_length=255),
        ),
    ]
