# Generated by Django 3.0.2 on 2021-04-07 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 4, 7, 18, 52, 38, 326960)),
        ),
    ]
