# Generated by Django 3.0.2 on 2021-04-07 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0002_auto_20210407_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 4, 7, 18, 53, 12, 302584)),
        ),
    ]
