# Generated by Django 3.0.2 on 2021-04-08 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0006_auto_20210408_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 4, 8, 0, 46, 55, 545448)),
        ),
    ]
