# Generated by Django 3.0.2 on 2021-04-24 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0022_auto_20210424_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 4, 24, 14, 8, 29, 257746)),
        ),
    ]
