# Generated by Django 3.0.2 on 2021-04-28 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0024_auto_20210428_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 4, 28, 16, 22, 16, 595237)),
        ),
    ]
