# Generated by Django 3.0.2 on 2021-04-30 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0026_auto_20210428_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 4, 30, 11, 48, 48, 478152)),
        ),
    ]
