# Generated by Django 3.0.2 on 2021-04-30 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0027_auto_20210430_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 4, 30, 17, 37, 56, 603936)),
        ),
    ]
