# Generated by Django 3.0.2 on 2021-04-30 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0028_auto_20210430_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 4, 30, 18, 3, 17, 791237)),
        ),
    ]
