# Generated by Django 3.0.2 on 2021-05-05 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0029_auto_20210430_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 5, 4, 23, 50, 28, 25164)),
        ),
    ]
