# Generated by Django 3.2.3 on 2021-06-24 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0030_auto_20210504_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 6, 23, 19, 33, 51, 293460)),
        ),
    ]
