# Generated by Django 3.0.2 on 2021-04-07 22:24

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del negocio')),
                ('logo', models.ImageField(upload_to='cfg/')),
                ('moneda', models.CharField(max_length=255, verbose_name='Moneda que se utilizará en la plataforma')),
                ('desc', models.TextField(verbose_name='Breve descripción de la empresa')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('instagram', models.CharField(blank=True, help_text='Opcional', max_length=255, verbose_name='Enlace a Instagram')),
                ('facebook', models.CharField(blank=True, help_text='Opcional', max_length=255, verbose_name='Enlace a Facebook')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': '01 - Configuraciones',
            },
        ),
    ]
