# Generated by Django 3.0.2 on 2021-04-08 04:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productos y servicios/', verbose_name='Imagen')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('price', models.FloatField(default=0, help_text='Opcional', verbose_name='Precio')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto o servicio',
                'verbose_name_plural': '02 - Productos y servicios',
            },
        ),
        migrations.CreateModel(
            name='ProductoPerks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Product')),
            ],
            options={
                'verbose_name': 'Información adicional',
                'verbose_name_plural': 'Informaciones adicionales',
            },
        ),
        migrations.CreateModel(
            name='GaleriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Resolución recomendada 1024x768', upload_to='productos/', verbose_name='Imagen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Product')),
            ],
            options={
                'verbose_name': 'Imagen de productos',
                'verbose_name_plural': 'Imágenes de productos',
            },
        ),
    ]
