# Generated by Django 3.0.2 on 2021-04-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_product_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descuento',
            field=models.FloatField(default=0),
        ),
    ]
