# Generated by Django 3.0.2 on 2021-04-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_product_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descuento',
        ),
    ]
