# Generated by Django 3.0.2 on 2021-04-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_remove_product_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': '02 - Tipos',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['tipo', 'id'], 'verbose_name': 'Producto o servicio', 'verbose_name_plural': '03 - Productos y servicios'},
        ),
        migrations.AddField(
            model_name='product',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Tipo', verbose_name='Clasificación'),
        ),
    ]
