# Generated by Django 3.0.2 on 2021-04-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20210408_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Tipo', verbose_name='Clasificación'),
        ),
    ]
