# Generated by Django 3.0.2 on 2021-04-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_seccionnosotrosperks'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionnosotrosperks',
            name='alineacion',
            field=models.CharField(choices=[('center', 'Al centro'), ('left', 'A la izquierda'), ('right', 'A la derecha'), ('justify', 'Justificar')], default='justify', max_length=255, verbose_name='Alineación del párrafo'),
        ),
    ]
