# Generated by Django 3.0.2 on 2021-04-24 18:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_auto_20210424_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaproducto',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Opcional'),
        ),
        migrations.AddField(
            model_name='galeriaproducto',
            name='titulo',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, verbose_name='Título'),
        ),
    ]
