# Generated by Django 3.0.2 on 2021-04-28 19:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20210424_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiacarrusel',
            name='tipo',
        ),
        migrations.AddField(
            model_name='historiacarrusel',
            name='autoplay',
            field=models.BooleanField(default=True, help_text='Mantenga activada esta opción si quiere que los videos se reproduzcan solos y en bucle', verbose_name='Reprodución automática'),
        ),
        migrations.AddField(
            model_name='historiacarrusel',
            name='muted',
            field=models.BooleanField(default=True, help_text='Mantenga activada esta opción si quiere mostrar videos sin sonido', verbose_name='Video mudo'),
        ),
        migrations.AddField(
            model_name='historiacarrusel',
            name='titulo',
            field=models.CharField(default='abdel.mp4', max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historia',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Opcional'),
        ),
    ]
