# Generated by Django 3.0.2 on 2021-04-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_auto_20210428_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, help_text='Opcional', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': '09 - Destinatarios',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255, verbose_name='Teléfono o E-mail')),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': '08 - Contactos',
            },
        ),
        migrations.RemoveField(
            model_name='historiacarrusel',
            name='titulo',
        ),
    ]
