# Generated by Django 3.0.2 on 2021-04-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_auto_20210428_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinatario',
            options={'verbose_name': 'Destinatario', 'verbose_name_plural': '06 - Destinatarios'},
        ),
        migrations.AlterModelOptions(
            name='reservacion',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': '05 - Contactos'},
        ),
    ]
