# Generated by Django 3.0.2 on 2021-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_auto_20210428_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255, verbose_name='Teléfono del comprador')),
                ('telefono2', models.CharField(max_length=255, verbose_name='Teléfono del receptor')),
                ('direccion', models.CharField(help_text='Dirección de quién lo recibe en Cuba', max_length=255, verbose_name='Dirección del receptor')),
                ('contenido', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Encargo',
                'verbose_name_plural': '07 - Encargos',
            },
        ),
    ]
