# Generated by Django 3.0.2 on 2021-04-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(help_text='Dirección de quién lo recibe en Cuba', max_length=255, verbose_name='Dirección a entregar'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono del receptor'),
        ),
    ]
