# Generated by Django 3.0.2 on 2021-04-30 22:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_auto_20210430_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='color2',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
