# Generated by Django 3.0.2 on 2021-05-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_configuracion_color2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiacarrusel',
            name='autoplay',
        ),
        migrations.RemoveField(
            model_name='historiacarrusel',
            name='muted',
        ),
        migrations.AlterField(
            model_name='historiacarrusel',
            name='multimedia',
            field=models.CharField(help_text='Link del video de YouTube tipo embed', max_length=700),
        ),
    ]
