# Generated by Django 3.2.3 on 2021-06-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_auto_20210504_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='paypal',
            field=models.CharField(default='ARPyFdnp1H1PssVANyVuDHoRWm7MA3jwMROIjX.R.Wt43uCIYZ17LIpr', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='porciento',
            field=models.FloatField(default=0, help_text='Porciento extra que se le agrega al precio de cada producto', verbose_name='Porcentaje de comisión'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='telegram',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, verbose_name='Contacto de Telegram'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, verbose_name='Contacto de WhatsApp'),
        ),
        migrations.AddField(
            model_name='product',
            name='calculado',
            field=models.BooleanField(default=False),
        ),
    ]
